# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0.xci
# IP: The module: 'CAM_PS_Configure_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0.xci
# IP: The module: 'CAM_PS_Configure_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Proj_ZYNQ/CAM_VGA/CAM_VGA.srcs/sources_1/bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CAM_PS_Configure_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
