# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PL_Constrs.xdc

# Block Designs: bd/CAM_PS_Configure/CAM_PS_Configure.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure || ORIG_REF_NAME==CAM_PS_Configure} -quiet] -quiet

# IP: bd/CAM_PS_Configure/ip/CAM_PS_Configure_processing_system7_0_0/CAM_PS_Configure_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure_processing_system7_0_0 || ORIG_REF_NAME==CAM_PS_Configure_processing_system7_0_0} -quiet] -quiet

# IP: bd/CAM_PS_Configure/ip/CAM_PS_Configure_axi_gpio_0_0/CAM_PS_Configure_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure_axi_gpio_0_0 || ORIG_REF_NAME==CAM_PS_Configure_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CAM_PS_Configure/ip/CAM_PS_Configure_ps7_0_axi_periph_0/CAM_PS_Configure_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure_ps7_0_axi_periph_0 || ORIG_REF_NAME==CAM_PS_Configure_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CAM_PS_Configure/ip/CAM_PS_Configure_rst_ps7_0_100M_0/CAM_PS_Configure_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure_rst_ps7_0_100M_0 || ORIG_REF_NAME==CAM_PS_Configure_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CAM_PS_Configure/ip/CAM_PS_Configure_auto_pc_0/CAM_PS_Configure_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CAM_PS_Configure_auto_pc_0 || ORIG_REF_NAME==CAM_PS_Configure_auto_pc_0} -quiet] -quiet

# XDC: bd/CAM_PS_Configure/CAM_PS_Configure_ooc.xdc
